call publish_city.bat   Abakan
call publish_city.bat   Achinsk
call publish_city.bat   Aleksandrov
call publish_city.bat   Aleksin
call publish_city.bat   Almati
call publish_city.bat   Almetyevsk
call publish_city.bat   Arhangelsk
call publish_city.bat   Astana
call publish_city.bat   Astrahan
call publish_city.bat   Balashikha
call publish_city.bat   Barnaul
call publish_city.bat   Batumi
call publish_city.bat   Belgorod
call publish_city.bat   Beloozersky
call publish_city.bat   Belovo
call publish_city.bat   Berezniki
call publish_city.bat   Bishkek
call publish_city.bat   Brest
call publish_city.bat   Bryansk
call publish_city.bat   Chapaevsk
call publish_city.bat   Cheboksary
call publish_city.bat   Chelyabinsk
call publish_city.bat   Cherepovets
call publish_city.bat   Chernushka
call publish_city.bat   Chishmyidavlekanovo
call publish_city.bat   Chistopol
call publish_city.bat   Dolgoprudny
call publish_city.bat   Domodedovo
call publish_city.bat   Donetsk
call publish_city.bat   Elista
call publish_city.bat   Gatchina
call publish_city.bat   Gelengik
call publish_city.bat   Gomel
call publish_city.bat   Gubkinsky
call publish_city.bat   Hantimansiysk
call publish_city.bat   Ishim
call publish_city.bat   Ivanteevka
call publish_city.bat   Kaliningrad
call publish_city.bat   Kaluga
call publish_city.bat   Kamyshlov
call publish_city.bat   Karaganda
call publish_city.bat   Kazan
call publish_city.bat   Khimki
call publish_city.bat   Kirov
call publish_city.bat   Kirovochepeck
call publish_city.bat   Klin
call publish_city.bat   Kokshektau
call publish_city.bat   Korkino
call publish_city.bat   Korolev
call publish_city.bat   Krasnodar
call publish_city.bat   Krasnogorsk
call publish_city.bat   Krasnoyarsk
call publish_city.bat   Kumertau
call publish_city.bat   Kursk
call publish_city.bat   Kyshtym
call publish_city.bat   Kyzyl
call publish_city.bat   Lipeck
call publish_city.bat   Lobnya
call publish_city.bat   Magnitogorsk
call publish_city.bat   Makhachkala
call publish_city.bat   Minsk
call publish_city.bat   Mitino
rem call publish_city.bat   Mytischi
call publish_city.bat   Naryanmar
call publish_city.bat   Neftejugansk
call publish_city.bat   Neftekamsk
call publish_city.bat   Nizhnekamsk
call publish_city.bat   Nizhnevartovsk
call publish_city.bat   Nizhnynovgorod
call publish_city.bat   Novokuznetsk
call publish_city.bat   Novosibirsk
call publish_city.bat   Novyurengoy
call publish_city.bat   Obninsk
call publish_city.bat   Odessa
call publish_city.bat   Odincovo
call publish_city.bat   Odintsovo
call publish_city.bat   Omsk
call publish_city.bat   Ozyorsk
call publish_city.bat   Pavlovskijposad
call publish_city.bat   Penza
call publish_city.bat   Pereslavl
call publish_city.bat   Perm
call publish_city.bat   Petrozavodsk
call publish_city.bat   Podolsk
call publish_city.bat   Pushkin
call publish_city.bat   Pushkino
call publish_city.bat   Ramenskoe
call publish_city.bat   Reutov
call publish_city.bat   Rostovdon
call publish_city.bat   Rostovvelikiy
call publish_city.bat   Ruzaevka
call publish_city.bat   Ryazan
call publish_city.bat   Saintpetersburg
call publish_city.bat   Samara
call publish_city.bat   Saransk
call publish_city.bat   Sarov
call publish_city.bat   Schelkovo
call publish_city.bat   Sergach
call publish_city.bat   Sergievposad
call publish_city.bat   Serpukhov
call publish_city.bat   Sevastopol
call publish_city.bat   Severodvinsk
call publish_city.bat   Sibai
call publish_city.bat   Sochi
call publish_city.bat   Sortavala
call publish_city.bat   Sovetsk
call publish_city.bat   Sovetsky
call publish_city.bat   Stavropol
rem call publish_city.bat   Surgut
call publish_city.bat   Syktyvkar
call publish_city.bat   Tagil
call publish_city.bat   Taraz
call publish_city.bat   Tatarsk
call publish_city.bat   Tazovskij_rajon
call publish_city.bat   Tolyatty
call publish_city.bat   Tomsk
rem call publish_city.bat   tstenburg
call publish_city.bat   Tula
call publish_city.bat   Tyumen
call publish_city.bat   Ufa
call publish_city.bat   Ulyanovsk
call publish_city.bat   Ust_ilimsk
call publish_city.bat   Velikijnovgorod
call publish_city.bat   Verkhnyayapyshma
call publish_city.bat   Vladimir
call publish_city.bat   Vladivostok
call publish_city.bat   Volgograd
call publish_city.bat   Vologda
call publish_city.bat   Volzhskiy
call publish_city.bat   Voronezh
call publish_city.bat   Yalta
call publish_city.bat   Yasnogorsk
call publish_city.bat   Yekaterinburg
call publish_city.bat   Yeysk
call publish_city.bat   Zelenograd
call publish_city.bat   Zhukovsky
                       