-- upgrade to version 2
delete from BUTTONS;
drop table if exists ORGANIZATION_CATEGORY;
CREATE TABLE ORGANIZATION_CATEGORY(
   _id INTEGER PRIMARY KEY AUTOINCREMENT,
   ID INTEGER NOT NULL,
   CATEGORY_ID INTEGER NOT NULL,
   ORGANIZATION_ID INTEGER NOT NULL, 
   POS INTEGER NOT NULL, 
   DELETED INTEGER, 
   UPDATED_AT INTEGER NOT NULL 
   );
CREATE UNIQUE INDEX IF NOT EXISTS ORGANIZATION_CATEGORY_UNIQUE1 ON ORGANIZATION_CATEGORY(ID);
CREATE UNIQUE INDEX IF NOT EXISTS ORGANIZATION_CATEGORY_UNIQUE2 ON ORGANIZATION_CATEGORY(CATEGORY_ID, ORGANIZATION_ID);
