-- distance support

ALTER TABLE ORGANIZATIONS ADD COLUMN sin_lat_rad REAL;
ALTER TABLE ORGANIZATIONS ADD COLUMN sin_lon_rad REAL;
ALTER TABLE ORGANIZATIONS ADD COLUMN cos_lat_rad REAL;
ALTER TABLE ORGANIZATIONS ADD COLUMN cos_lon_rad REAL;
