--  video support

 ALTER TABLE ORGANIZATIONS ADD COLUMN VIDEO TEXT;
 ALTER TABLE ORGANIZATIONS ADD COLUMN IS_VIDEO_HIDDEN NUMBER;


 ALTER TABLE EVENTS ADD COLUMN VIDEO TEXT;
 ALTER TABLE EVENTS ADD COLUMN IS_VIDEO_HIDDEN NUMBER;


 ALTER TABLE ACTIONS ADD COLUMN VIDEO TEXT;
 ALTER TABLE ACTIONS ADD COLUMN IS_VIDEO_HIDDEN NUMBER;


 ALTER TABLE NEWS ADD COLUMN VIDEO TEXT;
 ALTER TABLE NEWS ADD COLUMN IS_VIDEO_HIDDEN NUMBER;
